### ISSUE TITLE
Installation issue with git216-all-2.16.6-1.el7.ius.noarch.rpm

### ISSUE THREAD

**Issue by maggosourabh** [iusrepo/git216#15]
Hello Team,

I was using ius repo to install git2u-all packages during my base image compilation, but somehow since last few days it is now not working as latest rpm update from "https://centos7.iuscommunity.org/ius-release.rpm" is stating "git2u-all" is obsolete and start installing "git216-all" automatically. But somehow it is also failing as all required dependent packages are not available on "https://repo.ius.io/7/x86_64/packages/g/".

One such example is "emacs-git216 - 2.16.6-1.el7.ius" package which is required by git216-all package but is missing under "https://repo.ius.io/7/x86_64/packages/e/".

Is this planned to be corrected soon?.

Regards,

Sourabh Maggo

**Comment by weherdh** [comment]
Met the same issue, any workaround?

**Comment by weherdh** [comment]
Seems we can install the packages one by one as a workaround:

```
# cat ./installgit.sh
for p in emacs-git2u git216-gitk git-subtree git216-p4 git216-svn git216-gui git216-email git216-cvs
do
sudo yum install ${p}
done
```

**Comment by maggosourabh** [comment]
Yes @weherdh only issue for now is installing rest of the packages separately rather than using git216-all package.

I did used the same workaround for now.

**Comment by carlwgeorge** [comment]
This was caused by a slight oversight in that requirement when renaming the package to git216.  I have corrected it in the spec file and will publish the fixed RPMs soon.  Sorry for the trouble.

**Comment by carlwgeorge** [comment]
The update to resolve this has been published to the main repos.

**Comment by maggosourabh** [comment]
Thanks @carlwgeorge changes seems to be working now.
